import { jsPDF } from "jspdf";
(globalThis as any).__jsPDF = jsPDF;
import { downloadDocPdf } from "@/lib/axis-doc";
const spec = {
  title: "Weekly Operating Plan — Focus, Money and Training",
  subtitle: "Prepared for Aarav · 12–18 August 2026",
  summary: "You have 9 open tasks, 3 with deadlines this week, and spending is running 18% above your monthly average. Training is consistent but sleep is short. This plan sequences the week so deadlines land early and recovery improves.",
  footer: "Generated by AXIS from your logged data. Figures are estimates based on what you have tracked.",
  sections: [
    { heading: "Where you stand", kind: "keyvalue", lines: ["Open tasks | 9 (3 due this week)", "Spend this month | 1,240 of 1,050 average", "Training | 4 sessions, 210 minutes", "Sleep | 6.2h average"] },
    { heading: "Priorities this week", kind: "numbered", lines: ["Finish the physics lab report before Wednesday, it blocks two other tasks and carries the nearest deadline in your list.", "Submit the Stanford supplemental essay draft for review.", "Cut discretionary spending to 40 per day for the rest of the month."] },
    { heading: "Daily rhythm", kind: "table", lines: ["Day | Deep work | Training", "Mon | Lab report | Push", "Tue | Essay draft | Rest", "Wed | Submissions | Pull", "Thu | Review | Legs"] },
    { heading: "Money moves", kind: "bullets", lines: ["Pause food delivery for two weeks — it is your largest leak at roughly 210 this month.", "Move 100 to savings the day your allowance lands, before spending decisions happen.", "Review the two subscriptions you have not used in 30 days."] },
    { heading: "The one thing", kind: "callout", lines: ["Protect a 7.5 hour sleep window. Every other target in this plan gets easier when recovery is fixed first."] },
    { heading: "Notes", kind: "paragraphs", lines: ["Your protein intake is trending under target on training days, which limits the gains from four sessions a week. Add one high-protein meal on Mon, Wed and Thu.", "Reassess on Sunday: if spending is still above average, tighten the daily cap rather than cutting training or food quality."] },
  ],
};
(spec as any);
const out: string[] = [];
// stub browser save
const fs = await import("node:fs");
const origSave = (jsPDF as any).prototype.save;
(jsPDF as any).prototype.save = function (name: string) { fs.writeFileSync("/tmp/pdfqa/out.pdf", Buffer.from(this.output("arraybuffer"))); };
await downloadDocPdf(spec as any);
console.log("written", out.length);
